---

- name: Configure Gogs (install page)
  uri:
    url: "http://{{ gogs_hostname }}:{{ gogs_http_port }}/install"
    method: POST
    HEADER_Content-Type: "application/x-www-form-urlencoded"
    body: "db_type={{ gogs_db_type }}&db_host={{ gogs_db_host }}&db_user={{ gogs_db_user }}&db_passwd={{ gogs_db_pass }}&db_name={{ gogs_db_name }}&db_path={{ gogs_db_path }}&app_name={{ gogs_app_name }}&repo_root_path={{ gogs_repo_root_path }}&run_user={{ gogs_run_user }}&domain={{ gogs_hostname }}&ssh_port&{{ gogs_container_ssh_container_port if gogs_platform == 'docker' else gogs_ssh_port }}&http_port={{ gogs_container_http_container_port if gogs_platform == 'docker' else gogs_http_port }}&app_url=http://{{ gogs_hostname }}:{{ gogs_container_http_container_port if gogs_platform == 'docker' else gogs_http_port }}/&log_root_path={{ gogs_log_path }}&enable_captcha={{ gogs_enable_captcha }}&admin_name={{ gogs_admin_username }}&admin_passwd={{ gogs_admin_password }}&admin_confirm_passwd={{ gogs_admin_password }}&admin_email={{ gogs_admin_email }}"
    status_code: [200, 302, 404]
  register: gogs_install_resp
  changed_when: gogs_install_resp.status == 302

- include: wait.yml