---

- name: Install Gogs on Docker
  include_tasks: Docker/install_gogs.yml
  when: gogs_platform == 'Docker'

- name: Install Gogs on Linux
  include_tasks: install_gogs.yml
  when: (gogs_platform is undefined) or (gogs_platform != 'Docker')

- name: Configure Gogs
  include_tasks: configure_gogs.yml
