---
- name: Get repo - {{ repo_item.name }}
  uri:
    url: "http://{{ gogs_hostname }}:{{ gogs_http_port }}/api/v1/repos/{{ repo_item.owner }}/{{ repo_item.name }}"
    headers:
      Content-Type: application/json
      Authorization: "token {{ gogs_access_token }}"
    status_code: [200, 404]
  register: gogs_get_repo_resp

- name: Create repo - {{ repo_item.name }}
  uri:
    url: "http://{{ gogs_hostname }}:{{ gogs_http_port }}/api/v1/admin/users/{{ repo_item.owner }}/repos"
    method: POST
    headers:
      Content-Type: application/json
      Authorization: "token {{ gogs_access_token }}"
    body: "{{ lookup('template', 'templates/repo.json.j2') }}"
    body_format: json
    status_code: 201
  register: gogs_create_repo_resp
  when: gogs_get_repo_resp.status == 404
  changed_when: gogs_create_repo_resp.status == 201
