---
- name: Try to access Gogs
  uri:
    url: "http://{{ gogs_hostname }}:{{ gogs_http_port }}/"
    status_code: 200
  register: gogs_startup_resp
  until: (gogs_startup_resp is defined) and (gogs_startup_resp.status == 200)
  retries: "{{ gogs_connection_retries }}"
  delay: "{{ gogs_connection_delay }}"
