---
- name: Gather Docker specific variables
  include_vars: Docker.yml

- name: Check if Gogs data volume exists
  command: "docker volume inspect {{ gogs_container_data_volume }}"
  register: gogs_volume_inspect_output
  ignore_errors: true
  changed_when: false

- name: If not, create it
  command: "docker volume create --name {{ gogs_container_data_volume }}"
  when: gogs_volume_inspect_output|failed

- name: Start Gogs container
  docker_container:
    name: "{{ gogs_container_name }}"
    image: "{{ gogs_container_image }}"
    state: started
    published_ports:
      - "{{ gogs_http_port }}:{{ gogs_container_http_port }}"
      - "{{ gogs_ssh_port }}:{{ gogs_container_ssh_port }}"
    volumes:
      - "{{ gogs_container_data_volume }}:/data"
  register: gogs_container_result

- name: Wait for Gogs to start up
  include_tasks: ../wait.yml
